-- to insert only if table is empty
INSERT INTO role (name) SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT * FROM role WHERE role.name='ROLE_ADMIN');
INSERT INTO role (name) SELECT 'ROLE_STUDENT' WHERE NOT EXISTS (SELECT * FROM role WHERE role.name='ROLE_STUDENT');
INSERT INTO role (name) SELECT 'ROLE_TEACHER' WHERE NOT EXISTS (SELECT * FROM role WHERE role.name='ROLE_TEACHER');

-- FROM role;
--INSERT INTO role (name) VALUES ('ROLE_ADMIN');
--INSERT INTO role (name) VALUES ('ROLE_TEACHER');
--INSERT INTO role (name) VALUES ('ROLE_STUDENT');